export const LOAD_MOVIES = "LOAD_MOVIES";
export const ADD_FAVORITE_MOVIE = "ADD_FAVORITE_MOVIE";
export const DELETE_FAVORITE_MOVIE = "DELETE_FAVORITE_MOVIE";
export const CHANGE_SEARCH_WORD = "CHANGE_SEARCH_WORD";
export const CLEAN_MOVIES = "CLEAN_MOVIES";